clear all 
cd "C:\Users\meyne\OneDrive\Documents\Stage"
use "pivot_imp.dta"

factor Active_Learning Active_Listening Complex_Problem_Solving Coordination Critical_Thinking Equipment_Maintenance Equipment_Selection Installation Instructing Judgment_and_Decision_Making Learning_Strategies Management_of_Financial_Resource Management_of_Material_Resources Management_of_Personnel_Resource Mathematics Monitoring Negotiation Operation_and_Control Operations_Analysis Operations_Monitoring Persuasion Programming Quality_Control_Analysis Reading_Comprehension Repairing Science Service_Orientation Social_Perceptiveness Speaking Systems_Analysis Systems_Evaluation Technology_Design Time_Management Troubleshooting Writing, pcf
rotate
alpha Active_Learning Active_Listening Complex_Problem_Solving Coordination Critical_Thinking Equipment_Maintenance Equipment_Selection Installation Instructing Judgment_and_Decision_Making Learning_Strategies Management_of_Financial_Resource Management_of_Material_Resources Management_of_Personnel_Resource Mathematics Monitoring Negotiation Operation_and_Control Operations_Analysis Operations_Monitoring Persuasion Programming Quality_Control_Analysis Reading_Comprehension Repairing Science Service_Orientation Social_Perceptiveness Speaking Systems_Analysis Systems_Evaluation Technology_Design Time_Management Troubleshooting Writing, item
*alpha environ à égal 0.96 >= 0.7 donc on est content (importance)* 
*pareil pour level* 
